<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.yak.ops</groupId>
        <artifactId>yak-ops-plugin-datasource</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>yak-ops-plugin-datasource-all</artifactId>

    <name>Yak Ops All Datasource Plugins</name>
    <description>Runtime aggregation of all built-in Yak Ops datasource plugins</description>

    <dependencies>
        <dependency>
            <groupId>io.yak.ops</groupId>
            <artifactId>yak-ops-plugin-datasource-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.yak.ops</groupId>
            <artifactId>yak-ops-plugin-datasource-doris</artifactId>
        </dependency>
        <dependency>
            <groupId>io.yak.ops</groupId>
            <artifactId>yak-ops-plugin-datasource-elasticsearch</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.yak.ops</groupId>
            <artifactId>yak-ops-plugin-datasource-mongodb</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
