<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.yak.ops</groupId>
        <artifactId>yak-ops-plugin-datasource</artifactId>
        <version>1.0.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>yak-ops-plugin-datasource-mongodb</artifactId>

    <name>Yak Ops MongoDB Datasource Plugin</name>
    <description>MongoDB control-plane datasource integration for connection, catalog and preview</description>

    <dependencies>
        <dependency>
            <groupId>io.yak.ops</groupId>
            <artifactId>yak-ops-plugin-datasource-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongodb-driver-sync</artifactId>
            <version>4.11.5</version>
        </dependency>
    </dependencies>
</project>
